name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: store_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: store
        options: >-
          --health-cmd="pg_isready -U store_user -d store"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Flyway CLI
      run: |
        curl -L -o flyway.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz"
        tar -xzf flyway.tar.gz
        sudo ln -s "$(pwd)/flyway-9.22.3/flyway" /usr/local/bin/flyway

    - name: Run Flyway migrations
      run: |
        flyway -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
               -user="${{ secrets.DB_USER }}" \
               -password="${{ secrets.DB_PASSWORD }}" \
               -locations="filesystem:migrations" \
               migrate

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
